import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Danelfin</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1 className={styles.title}>Danelfin</h1>
				<nav className={styles.nav}>
					<Link href="/login">
						<a>Login</a>
					</Link>
					<Link href="/users">
						<a>Users</a>
					</Link>
				</nav>
			</main>
		</div>
	);
}
